[tox]
envlist = 
  {py312}-redis460
  {py313}-redis460
  {py314}-redis460

[testenv]
setenv =
    PROMETHEUS_REDIS_URI=redis://localhost:6379/12
deps =
    pytest==9.1.1
    redis460: redis==4.6.0
commands =
    pytest -vv